#!/usr/bin/env node
'use strict';

const assert = require('assert');
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const read = rel => fs.readFileSync(path.join(root, rel), 'utf8');
const json = rel => JSON.parse(read(rel));

function main() {
  assert(fs.existsSync(path.join(root, 'board/learning-cases/README.md')), 'learning-cases README must exist');
  assert(fs.existsSync(path.join(root, 'board/learning-cases/ui-optimization-cases.md')), 'ui optimization cases file must exist');

  const cases = read('board/learning-cases/ui-optimization-cases.md');
  for (const word of ['来源', '事件日志', '场景', '现象', '根因/判断', '改法', '验证', '可复用原则']) {
    assert(cases.includes(word), `case template missing ${word}`);
  }

  const readme = read('board/learning-cases/README.md');
  assert(readme.includes('`来源`、`验证`、`可复用原则` 三项不得省略'), 'README must require source, validation, reusable principle');
  assert(readme.includes('能指导后续不同项目/页面/agent 决策'), 'README must require generic reusable principles');
  assert(readme.includes('参考案例:'), 'README must require visible case references');
  assert(readme.includes('learning_case.appended'), 'README must require learning case eventlog entries');
  assert(readme.includes('secretary -> CEO -> supervisor'), 'README must preserve front-door event chain evidence');

  const uiPrompt = read('shared/agents/ui-optimizer/prompt.md');
  assert(uiPrompt.includes('board/learning-cases/ui-optimization-cases.md'), 'ui optimizer prompt must require case persistence');
  assert(uiPrompt.includes('来源→场景→现象→根因/判断→改法→验证→可复用原则'), 'ui optimizer prompt must enforce case structure');
  assert(uiPrompt.includes('learning_case.appended'), 'ui optimizer prompt must require event logging');
  assert(uiPrompt.includes('KeyboardEvent.isComposing'), 'ui optimizer prompt must preserve the Chinese IME submit rule from learning cases');
  assert(uiPrompt.includes('aria-label'), 'ui optimizer prompt must preserve stable screen-reader naming guidance');
  assert(uiPrompt.includes('不能只靠 `title` 兜底'), 'ui optimizer prompt must not allow title-only accessibility fallback');
  assert(uiPrompt.includes('name/role/value'), 'ui optimizer prompt must require name/role/value checks for accessibility and grounding');
  assert(uiPrompt.includes('稳定程序化名称'), 'ui optimizer prompt must preserve stable programmatic naming guidance');
  assert(uiPrompt.includes('被截断、折叠或只显示符号'), 'ui optimizer prompt must cover truncated, collapsed, or symbolic monitoring text');
  assert(uiPrompt.includes('聚合 `aria-label`'), 'ui optimizer prompt must require aggregate aria-label for dense monitoring text');
  assert(uiPrompt.includes('role=list/listitem/group'), 'ui optimizer prompt must require list/listitem/group semantics for chained dense UI nodes');
	  assert(uiPrompt.includes('监控/任务板核心状态'), 'ui optimizer prompt must preserve monitoring-panel readability guidance');
	  assert(uiPrompt.includes('两行核心语义可读'), 'ui optimizer prompt must require at least two readable lines for core monitoring state');
	  assert(uiPrompt.includes('错误反馈可发现性'), 'ui optimizer prompt must preserve error feedback discoverability guidance');
	  assert(uiPrompt.includes('高频主操作反馈'), 'ui optimizer prompt must preserve high-frequency primary action feedback guidance');
	  assert(uiPrompt.includes('不能静默失败'), 'ui optimizer prompt must reject silent primary action failures');
	  assert(uiPrompt.includes('aria-busy'), 'ui optimizer prompt must synchronize busy state through aria-busy');
	  assert(uiPrompt.includes('visible text'), 'ui optimizer prompt must synchronize visible text with programmatic busy names');
	  assert(uiPrompt.includes('任务卡 summary 聚合名称'), 'ui optimizer prompt must require aggregate names for task-card summaries');
	  assert(uiPrompt.includes('普通队列项'), 'ui optimizer prompt must cover ordinary queue item summaries');
	  assert(uiPrompt.includes('CEO 卡'), 'ui optimizer prompt must cover CEO task-card summaries');
	  assert(uiPrompt.includes('运行中卡'), 'ui optimizer prompt must cover running task-card summaries');
	  assert(uiPrompt.includes('排队卡'), 'ui optimizer prompt must cover queued task-card summaries');
	  assert(uiPrompt.includes('当前进展/等待原因'), 'ui optimizer prompt must include progress or wait reason in aggregate task-card names');
	  assert(uiPrompt.includes('忙碌控件和监控摘要三同步'), 'ui optimizer prompt must preserve 13:57 busy-control and monitoring-summary guidance');
	  assert(uiPrompt.includes('批量按钮'), 'ui optimizer prompt must cover bulk buttons during busy state');
	  assert(uiPrompt.includes('启用按钮'), 'ui optimizer prompt must cover enable buttons during busy state');
	  assert(uiPrompt.includes('单项动作按钮'), 'ui optimizer prompt must cover single action buttons during busy state');
	  assert(uiPrompt.includes('queueHint'), 'ui optimizer prompt must cover queueHint programmatic naming');
	  assert(uiPrompt.includes('派单反馈'), 'ui optimizer prompt must cover dispatch feedback programmatic naming');
	  assert(uiPrompt.includes('模型用量窗口'), 'ui optimizer prompt must cover model-usage window aggregate names');
	  assert(uiPrompt.includes('title'), 'ui optimizer prompt must synchronize busy tooltip/title');
	  assert(uiPrompt.includes('状态 · 执行方 · 摘要 · meta · #ID'), 'ui optimizer prompt must require queue summary aggregate text');
	  assert(uiPrompt.includes('状态·执行方·摘要·meta·#ID'), 'ui optimizer prompt must preserve compact queue summary aggregate phrase');
	  assert(uiPrompt.includes('监控卡片层聚合名称和刷新同步'), 'ui optimizer prompt must preserve 14:58 monitoring-card aggregate-name guidance');
	  assert(uiPrompt.includes('工位卡 role=group'), 'ui optimizer prompt must require workstation cards to expose role=group');
	  assert(uiPrompt.includes('模型用量卡聚合 `aria-label`'), 'ui optimizer prompt must require model-usage cards to expose aggregate aria-labels');
	  assert(uiPrompt.includes('模型/用量/调用/状态/额度'), 'ui optimizer prompt must include model, usage, calls, status, and quota in model-usage card labels');
	  assert(uiPrompt.includes('错误态 role=alert'), 'ui optimizer prompt must require alert semantics for model-usage error state');
	  assert(uiPrompt.includes('完整失败原因'), 'ui optimizer prompt must synchronize complete failure reason into programmatic error feedback');
	  assert(uiPrompt.includes('llmHint'), 'ui optimizer prompt must cover llmHint aria-label error details');
	  assert(uiPrompt.includes('动态刷新路径'), 'ui optimizer prompt must verify dynamic refresh paths keep aggregate names fresh');
	  assert(uiPrompt.includes('setInterval/fetch/WebSocket/onmessage'), 'ui optimizer prompt must name common dynamic refresh callbacks');
	  assert(uiPrompt.includes('title-only'), 'ui optimizer prompt must reject title-only regressions after refresh');
	  assert(uiPrompt.includes('候选审批卡与监控空态/错误态'), 'ui optimizer prompt must preserve 15:58 approval-card and empty-state guidance');
	  assert(uiPrompt.includes('15:58 专属检查'), 'ui optimizer prompt must keep 15:58 boundary separate from earlier cases');
	  assert(uiPrompt.includes('候选审批/启用卡'), 'ui optimizer prompt must cover approval and enable cards');
	  assert(uiPrompt.includes('inline approval card'), 'ui optimizer prompt must name inline approval card semantics');
	  assert(uiPrompt.includes('左侧强调边'), 'ui optimizer prompt must require visible boundary for approval cards');
	  assert(uiPrompt.includes('来源/目标/项目/标题/摘要/动作'), 'ui optimizer prompt must require full approval-card aggregate names');
	  assert(uiPrompt.includes('任务板摘要'), 'ui optimizer prompt must cover task-board summary naming');
	  assert(uiPrompt.includes('queueHint` 刷新路径'), 'ui optimizer prompt must verify queueHint refresh path names');
	  assert(uiPrompt.includes('模型用量空态'), 'ui optimizer prompt must cover model-usage empty states');
		  assert(uiPrompt.includes('读取中/暂无/读取失败'), 'ui optimizer prompt must name loading, empty, and failure states');
		  assert(uiPrompt.includes('live region'), 'ui optimizer prompt must require live semantics for monitoring empty and error states');
		  assert(uiPrompt.includes('role=status/alert'), 'ui optimizer prompt must require status or alert semantics for empty and error states');
		  assert(uiPrompt.includes('主操作忙碌态和监控空态名称恢复'), 'ui optimizer prompt must preserve 00:59 busy-state and monitoring-empty-state restoration guidance');
		  assert(uiPrompt.includes('00:59 专属检查'), 'ui optimizer prompt must keep 00:59 boundary separate from earlier cases');
		  assert(uiPrompt.includes("title='派单中,等待队列接收'"), 'ui optimizer prompt must require dispatch busy title text');
		  assert(uiPrompt.includes('finally 恢复原 title'), 'ui optimizer prompt must require final title restoration after dispatch busy state');
		  assert(uiPrompt.includes('队列错误态'), 'ui optimizer prompt must cover queue error alert semantics');
		  assert(uiPrompt.includes('服务器机房空态/错误态'), 'ui optimizer prompt must cover server-room empty and error states');
		  assert(uiPrompt.includes('模型用量 hint 的初始 DOM 与 loading 分支'), 'ui optimizer prompt must cover model-usage hint initial DOM and loading branch');
		  assert(uiPrompt.includes('旧状态残留'), 'ui optimizer prompt must reject stale programmatic names after refresh');
		  assert(uiPrompt.includes('视觉空态和概览计数 name/role/value'), 'ui optimizer prompt must preserve 02:02 visual empty-state and overview-count guidance');
		  assert(uiPrompt.includes('02:02 专属检查'), 'ui optimizer prompt must keep 02:02 boundary separate from earlier cases');
		  assert(uiPrompt.includes('任务板空态'), 'ui optimizer prompt must cover task-board empty states');
		  assert(uiPrompt.includes('左侧工位概览'), 'ui optimizer prompt must cover the left workstation overview');
		  assert(uiPrompt.includes('办公室工位概览'), 'ui optimizer prompt must cover office workstation overview');
		  assert(uiPrompt.includes('暂无进行中/暂无排队中/暂无可启用候选/暂无过往记录'), 'ui optimizer prompt must name concrete task-board empty states');
		  assert(uiPrompt.includes('裸 `.tb-empty`'), 'ui optimizer prompt must reject bare tb-empty placeholders');
		  assert(uiPrompt.includes('taskBoardEmpty(text)'), 'ui optimizer prompt must prefer the shared task-board empty-state helper');
		  assert(uiPrompt.includes('概览容器必须声明 `role=list`'), 'ui optimizer prompt must require role=list on overview containers');
		  assert(uiPrompt.includes('状态胶囊/chip'), 'ui optimizer prompt must cover status capsules and chips');
		  assert(uiPrompt.includes('role=listitem'), 'ui optimizer prompt must require listitem semantics on status chips');
		  assert(uiPrompt.includes('aria-hidden'), 'ui optimizer prompt must hide decorative animation dots');
		  assert(uiPrompt.includes('“没有数据”和计数状态'), 'ui optimizer prompt must treat no-data and count states as name/role/value states');
		  assert(uiPrompt.includes('动态链路图和操作反馈完整程序化状态'), 'ui optimizer prompt must preserve 02:59 flow-map and feedback full-state guidance');
		  assert(uiPrompt.includes('02:59 专属检查'), 'ui optimizer prompt must keep 02:59 boundary separate from earlier cases');
		  assert(uiPrompt.includes('mapHint'), 'ui optimizer prompt must cover mapHint live status naming');
		  assert(uiPrompt.includes('flowmap'), 'ui optimizer prompt must cover flowmap container naming');
		  assert(uiPrompt.includes('role=group/tabindex/title/aria-label'), 'ui optimizer prompt must require flowmap group, focus, title, and aria-label semantics');
		  assert(uiPrompt.includes('键盘焦点环'), 'ui optimizer prompt must require a visible keyboard focus ring for the flow map');
		  assert(uiPrompt.includes('链路交接刷新'), 'ui optimizer prompt must verify handoff refresh updates programmatic names');
		  assert(uiPrompt.includes('容器聚合名称'), 'ui optimizer prompt must require aggregate names on monitoring containers');
		  assert(uiPrompt.includes('compactFeedbackText'), 'ui optimizer prompt must preserve compact visible feedback with full hidden text');
		  assert(uiPrompt.includes('完整文本必须保留到 `title/aria-label`'), 'ui optimizer prompt must keep full feedback text in title and aria-label');
		  assert(uiPrompt.includes('120 字'), 'ui optimizer prompt must reject truncating complete feedback state to 120 chars');
		  assert(uiPrompt.includes('实时监控图、live hint 和主操作反馈'), 'ui optimizer prompt must preserve the 02:59 reusable principle');
		  assert(uiPrompt.includes('动态进展和额度窗口完整状态结构'), 'ui optimizer prompt must preserve 04:03 task-progress and quota-window state-structure guidance');
		  assert(uiPrompt.includes('04:03 专属检查'), 'ui optimizer prompt must keep 04:03 boundary separate from earlier cases');
		  assert(uiPrompt.includes('任务板进展行'), 'ui optimizer prompt must cover task-board progress rows');
		  assert(uiPrompt.includes('running bar/进展运行条'), 'ui optimizer prompt must cover the progress running bar');
		  assert(uiPrompt.includes('模型用量额度窗口'), 'ui optimizer prompt must cover model-usage quota windows');
		  assert(uiPrompt.includes('任务进展行必须有 `role=group`'), 'ui optimizer prompt must require role=group on task progress rows');
		  assert(uiPrompt.includes('进展运行条必须有 `role=status/title/aria-label`'), 'ui optimizer prompt must require status, title, and aria-label on progress motion bars');
		  assert(uiPrompt.includes('内部动画条或 `<i>` 装饰必须 `aria-hidden`'), 'ui optimizer prompt must hide progress animation decoration from accessibility trees');
		  assert(uiPrompt.includes('`role=list` 容器和 `role=listitem` 子项'), 'ui optimizer prompt must require list/listitem structure for quota windows');
			  assert(uiPrompt.includes('每个窗口项保留完整 `title/aria-label`'), 'ui optimizer prompt must keep complete title and aria-label on each quota window item');
			  assert(uiPrompt.includes('内部持续变化、重复列表化或带动画的状态片段'), 'ui optimizer prompt must cover dynamic, repeated, and animated inner monitoring fragments');
			  assert(uiPrompt.includes('也要补完整 name/role/value'), 'ui optimizer prompt must require complete name/role/value on inner state fragments');
			  assert(uiPrompt.includes('动态短状态和空态反馈同步'), 'ui optimizer prompt must preserve 05:14 dynamic-short-state and empty-feedback guidance');
			  assert(uiPrompt.includes('05:14 专属检查'), 'ui optimizer prompt must keep 05:14 boundary separate from earlier cases');
			  assert(uiPrompt.includes('任务时长胶囊'), 'ui optimizer prompt must cover task duration pills');
			  assert(uiPrompt.includes('动态短状态刷新'), 'ui optimizer prompt must cover dynamic short-state refresh paths');
			  assert(uiPrompt.includes('data-duration-label'), 'ui optimizer prompt must require duration label metadata for live refresh');
			  assert(uiPrompt.includes('定时刷新路径也要同点更新 `title/aria-label`'), 'ui optimizer prompt must refresh duration title and aria-label in timer paths');
			  assert(uiPrompt.includes('行级 `title` 不得缺失'), 'ui optimizer prompt must require row-level progress titles for compact progress text');
			  assert(uiPrompt.includes('模型用量空列表'), 'ui optimizer prompt must cover empty model usage lists');
			  assert(uiPrompt.includes('header hint'), 'ui optimizer prompt must cover model usage header hint semantics');
			  assert(uiPrompt.includes('可见“暂无数据”'), 'ui optimizer prompt must require visible empty data status');
			  assert(uiPrompt.includes('模型用量: 暂无模型用量数据 · 更新时间'), 'ui optimizer prompt must preserve complete model usage empty-state title and aria-label');
			  assert(uiPrompt.includes('非图片附件'), 'ui optimizer prompt must cover non-image attachment input');
			  assert(uiPrompt.includes('不得静默失败'), 'ui optimizer prompt must reject silent invalid attachment failures');
			  assert(uiPrompt.includes('就近反馈'), 'ui optimizer prompt must require nearby feedback for invalid attachment input');
				  assert(uiPrompt.includes('未识别到图片附件'), 'ui optimizer prompt must name the no-image feedback text');
				  assert(uiPrompt.includes('已跳过 N 个非图片文件'), 'ui optimizer prompt must name skipped non-image attachment feedback');
				  assert(uiPrompt.includes('空态和输入失败是一等监控/操作反馈状态'), 'ui optimizer prompt must treat empty and invalid-input states as first-class feedback');
				  assert(uiPrompt.includes('附件列表和头部监控短状态稳定名称'), 'ui optimizer prompt must preserve 06:15 attachment-list and header-short-state guidance');
				  assert(uiPrompt.includes('06:15 专属检查'), 'ui optimizer prompt must keep 06:15 boundary separate from earlier cases');
				  assert(uiPrompt.includes('底部图片附件托盘'), 'ui optimizer prompt must cover the bottom image attachment tray');
				  assert(uiPrompt.includes('页头事件更新时间/失败态'), 'ui optimizer prompt must cover header timestamp success and failure states');
				  assert(uiPrompt.includes('任务板短进展完整名称'), 'ui optimizer prompt must cover complete names for compact task-board progress');
				  assert(uiPrompt.includes('不要重复 05:14 的非图片附件反馈'), 'ui optimizer prompt must keep 06:15 separate from the 05:14 non-image feedback rule');
				  assert(uiPrompt.includes('不要重复 05:14'), 'ui optimizer prompt must preserve the 06:15/05:14 boundary');
				  assert(uiPrompt.includes('`role=list`、空态/聚合 `aria-label`'), 'ui optimizer prompt must require list role and aggregate aria-label on attachment tray');
				  assert(uiPrompt.includes('每张缩略图必须有 `role=listitem`'), 'ui optimizer prompt must require listitem semantics on every attachment thumbnail');
				  assert(uiPrompt.includes('视觉数量如“n 张图片”应标为装饰'), 'ui optimizer prompt must hide the visual attachment count as decoration');
				  assert(uiPrompt.includes('页头 `#ts`'), 'ui optimizer prompt must name the header timestamp element');
				  assert(uiPrompt.includes('初始、成功刷新和失败分支'), 'ui optimizer prompt must check timestamp initial, success, and failure branches');
				  assert(uiPrompt.includes('`role=status/alert`'), 'ui optimizer prompt must require status or alert semantics for header timestamp states');
				  assert(uiPrompt.includes('aria-live/aria-atomic'), 'ui optimizer prompt must preserve live and atomic semantics for header timestamp states');
				  assert(uiPrompt.includes('事件流失败详情只放进 hover `title`'), 'ui optimizer prompt must reject title-only event-stream failure detail');
				  assert(uiPrompt.includes('progressTitle'), 'ui optimizer prompt must cover progressTitle programmatic names');
				  assert(uiPrompt.includes('progressTitle || progressLabel'), 'ui optimizer prompt must require compact progress aria labels to use complete progressTitle fallback');
				  assert(uiPrompt.includes('附件托盘、页头更新时间和短进展这些小状态'), 'ui optimizer prompt must treat small attachment/header/progress states as full name-role-value surfaces');
				  assert(uiPrompt.includes('动态刷新路径与初始 DOM 同点更新'), 'ui optimizer prompt must require dynamic refresh paths to match the initial DOM names');
				  assert(uiPrompt.includes('弹窗状态和图谱装饰件同步语义'), 'ui optimizer prompt must preserve 07:13 modal-state and graph-decoration guidance');
				  assert(uiPrompt.includes('07:13 专属检查'), 'ui optimizer prompt must keep 07:13 boundary separate from earlier cases');
				  assert(uiPrompt.includes('版本历史弹窗状态'), 'ui optimizer prompt must cover version history modal states');
				  assert(uiPrompt.includes('链路图节点视觉装饰件'), 'ui optimizer prompt must cover flow-map node visual decorations');
				  assert(uiPrompt.includes('不要重复 06:15 的附件托盘'), 'ui optimizer prompt must keep 07:13 separate from the 06:15 attachment/header/progress rule');
				  assert(uiPrompt.includes('versionStateHtml()'), 'ui optimizer prompt must name the shared version history state renderer');
				  assert(uiPrompt.includes('加载中、暂无历史、加载失败'), 'ui optimizer prompt must cover loading, empty, and failure modal branches');
				  assert(uiPrompt.includes('加载动画点必须 `aria-hidden`'), 'ui optimizer prompt must hide modal loading animation dots');
				  assert(uiPrompt.includes('端口 pin/pout'), 'ui optimizer prompt must cover flow-map node pin and pout decorations');
				  assert(uiPrompt.includes('状态点'), 'ui optimizer prompt must cover flow-map node state dots');
				  assert(uiPrompt.includes('只服务视觉定位或动效'), 'ui optimizer prompt must distinguish visual positioning and motion decorations from content');
				  assert(uiPrompt.includes('aria-hidden="true"'), 'ui optimizer prompt must require aria-hidden true on graph decorations');
					  assert(uiPrompt.includes('动态弹窗状态、空态、失败态'), 'ui optimizer prompt must treat dynamic modal states as full name-role-value surfaces');
					  assert(uiPrompt.includes('视觉装饰件要隐藏'), 'ui optimizer prompt must require decorative visual parts to be hidden from accessibility trees');
					  assert(uiPrompt.includes('容器聚合名称成为唯一稳定语义'), 'ui optimizer prompt must make aggregate container names the stable semantic source for decorated graph nodes');
					  assert(uiPrompt.includes('控制室监控行和版本分组完整程序化名称'), 'ui optimizer prompt must preserve 08:14 control-room and version-group naming guidance');
					  assert(uiPrompt.includes('08:14 专属检查'), 'ui optimizer prompt must keep 08:14 boundary separate from earlier cases');
					  assert(uiPrompt.includes('版本历史分组按钮'), 'ui optimizer prompt must cover version history group buttons');
					  assert(uiPrompt.includes('/control-room'), 'ui optimizer prompt must cover the control-room monitoring page');
					  assert(uiPrompt.includes('不要重复 07:13 的弹窗状态/图谱装饰件规则'), 'ui optimizer prompt must keep 08:14 separate from the 07:13 modal and graph-decoration rule');
					  assert(uiPrompt.includes('`g.x 系列`'), 'ui optimizer prompt must require complete version-group series naming');
					  assert(uiPrompt.includes('进行中/已完成'), 'ui optimizer prompt must require version group state in programmatic names');
					  assert(uiPrompt.includes('版本区间'), 'ui optimizer prompt must include version range in group labels');
					  assert(uiPrompt.includes('更新次数'), 'ui optimizer prompt must include update count in version group labels');
					  assert(uiPrompt.includes('同步 `aria-expanded`'), 'ui optimizer prompt must require aria-expanded sync for collapsible version groups');
					  assert(uiPrompt.includes('控制室主区必须有 `aria-live` 与 `aria-busy`'), 'ui optimizer prompt must require live and busy semantics on the control-room main region');
					  assert(uiPrompt.includes('读取失败和时间戳'), 'ui optimizer prompt must cover control-room failure and timestamp states');
					  assert(uiPrompt.includes('系统智能体、Runner、声明式流程和引擎事件流'), 'ui optimizer prompt must cover all control-room monitoring rows');
					  assert(uiPrompt.includes('`role=region/list/listitem`'), 'ui optimizer prompt must require region/list/listitem semantics for control-room rows');
					  assert(uiPrompt.includes('名称、runner、角色、读取路径、节点数、文件、事件序号/类型/节点'), 'ui optimizer prompt must require full aggregate row labels for control-room monitoring rows');
					  assert(uiPrompt.includes('转义 attribute 文本中的双引号'), 'ui optimizer prompt must require attribute escaping for complete programmatic labels');
					  assert(uiPrompt.includes('不能只依赖视觉行文本或截断标题'), 'ui optimizer prompt must reject visual row text or truncated titles as the only semantic source');
					  assert(uiPrompt.includes('策略提示和操作失败反馈完整语义'), 'ui optimizer prompt must preserve 09:11 strategy-tip and failure-feedback semantic guidance');
					  assert(uiPrompt.includes('09:11 专属检查'), 'ui optimizer prompt must keep 09:11 boundary separate from earlier cases');
					  assert(uiPrompt.includes('模型用量策略提示'), 'ui optimizer prompt must cover model-usage strategy tips');
					  assert(uiPrompt.includes('模型用量进度条/读取中动效'), 'ui optimizer prompt must cover model-usage progress and loading motion');
					  assert(uiPrompt.includes('任务板/派单失败反馈'), 'ui optimizer prompt must cover task-board and dispatch failure feedback');
					  assert(uiPrompt.includes('不要重复 08:14 的版本分组/control-room 行级名称'), 'ui optimizer prompt must keep 09:11 separate from the 08:14 version/control-room rule');
					  assert(uiPrompt.includes('策略容器必须有 `role=list`'), 'ui optimizer prompt must require list semantics on strategy-tip containers');
					  assert(uiPrompt.includes('每条策略必须有 `role=listitem`'), 'ui optimizer prompt must require listitem semantics on each strategy tip');
					  assert(uiPrompt.includes('模型用量 progressbar 填充 `<i>`'), 'ui optimizer prompt must cover model-usage progressbar fill decoration');
					  assert(uiPrompt.includes('读取中 loading-dot'), 'ui optimizer prompt must cover loading-dot decoration semantics');
					  assert(uiPrompt.includes('纯装饰动效必须 `aria-hidden="true"`'), 'ui optimizer prompt must hide purely decorative loading and progress motion');
					  assert(uiPrompt.includes('setInlineStatus()'), 'ui optimizer prompt must cover the inline status helper');
					  assert(uiPrompt.includes('setComposeFeedback()'), 'ui optimizer prompt must cover the compose feedback helper');
					  assert(uiPrompt.includes("tone==='err'"), 'ui optimizer prompt must use error tone as the alert trigger');
					  assert(uiPrompt.includes('role=alert'), 'ui optimizer prompt must upgrade error feedback to alert semantics');
					  assert(uiPrompt.includes('aria-live=assertive'), 'ui optimizer prompt must use assertive live regions for error feedback');
						  assert(uiPrompt.includes('role=status'), 'ui optimizer prompt must restore ordinary feedback to status semantics');
						  assert(uiPrompt.includes('aria-live=polite'), 'ui optimizer prompt must restore ordinary feedback to polite live regions');
						  assert(uiPrompt.includes('错误态不仅要变红'), 'ui optimizer prompt must reject color-only error feedback');
						  assert(uiPrompt.includes('监控提示、装饰动效和操作失败反馈'), 'ui optimizer prompt must preserve the 09:11 reusable principle');
						  assert(uiPrompt.includes('模型用量内部状态结构'), 'ui optimizer prompt must preserve 10:11 model-usage inner-state structure guidance');
						  assert(uiPrompt.includes('10:11 专属检查'), 'ui optimizer prompt must keep 10:11 boundary separate from earlier cases');
						  assert(uiPrompt.includes('header hint'), 'ui optimizer prompt must cover model-usage header hint state');
						  assert(uiPrompt.includes('百分比焦点块'), 'ui optimizer prompt must cover the model-usage percentage focus block');
						  assert(uiPrompt.includes('三项指标明细'), 'ui optimizer prompt must cover the three model-usage metric details');
						  assert(uiPrompt.includes('不要重复 09:11 的策略提示/进度条装饰/派单失败反馈'), 'ui optimizer prompt must keep 10:11 separate from the 09:11 strategy/progress/failure rule');
						  assert(uiPrompt.includes('setLlmHint()'), 'ui optimizer prompt must name the shared model-usage hint helper');
						  assert(uiPrompt.includes('visible text、`title`、`aria-label`、`role`、`aria-live` 与 `aria-atomic`'), 'ui optimizer prompt must synchronize all header hint visible and programmatic fields');
						  assert(uiPrompt.includes('读取中/不可用/暂无数据/已更新'), 'ui optimizer prompt must cover all model-usage hint dynamic paths');
						  assert(uiPrompt.includes('header hint 要有 `data-feedback`'), 'ui optimizer prompt must require feedback styling on the header hint');
						  assert(uiPrompt.includes('info/warn/err'), 'ui optimizer prompt must distinguish model-usage hint feedback tones');
						  assert(uiPrompt.includes('百分比焦点块必须有 `role=group/title/aria-label`'), 'ui optimizer prompt must require group semantics for the percentage focus block');
						  assert(uiPrompt.includes('progressLabel'), 'ui optimizer prompt must reuse full progress labels in the focus block');
						  assert(uiPrompt.includes('“当前用量 / 调用 / 来源”'), 'ui optimizer prompt must name the three model-usage metrics');
						  assert(uiPrompt.includes('指标容器必须有 `role=list`'), 'ui optimizer prompt must require list semantics on the metric container');
						  assert(uiPrompt.includes('每个 `.llm-metric` 必须有 `role=listitem/title/aria-label`'), 'ui optimizer prompt must require listitem semantics on every model-usage metric');
						  assert(uiPrompt.includes('内部持续变化的额度焦点、指标列表和 header 状态 hint'), 'ui optimizer prompt must preserve the 10:11 reusable principle');
						  assert(uiPrompt.includes('截断按钮和模型用量内部文本分层'), 'ui optimizer prompt must preserve 11:20 compact-button and internal-text layering guidance');
						  assert(uiPrompt.includes('11:20 专属检查'), 'ui optimizer prompt must keep 11:20 boundary separate from earlier cases');
						  assert(uiPrompt.includes('头部版本徽章'), 'ui optimizer prompt must cover the header version badge');
						  assert(uiPrompt.includes('模型用量百分比焦点块内部重复文本'), 'ui optimizer prompt must cover duplicate inner text in the model-usage focus block');
						  assert(uiPrompt.includes('计费胶囊'), 'ui optimizer prompt must cover billing capsule complete names');
						  assert(uiPrompt.includes('不要重复 10:11 的 header hint/指标 list/listitem 结构'), 'ui optimizer prompt must keep 11:20 separate from the 10:11 header and metric rule');
						  assert(uiPrompt.includes('不要重复 08:14 的版本历史分组按钮规则'), 'ui optimizer prompt must keep 11:20 separate from the 08:14 version-group rule');
						  assert(uiPrompt.includes('版本徽章是紧凑 `role=button`'), 'ui optimizer prompt must identify the compact version badge button');
						  assert(uiPrompt.includes('初始 DOM 与 `pollVersion()`'), 'ui optimizer prompt must verify initial and pollVersion refresh labels');
						  assert(uiPrompt.includes('打开版本历史动作'), 'ui optimizer prompt must include the version-history action in programmatic names');
						  assert(uiPrompt.includes('最近变更/更新时间'), 'ui optimizer prompt must include recent change or update time in version badge labels');
						  assert(uiPrompt.includes('可见版本号或 hover `title`'), 'ui optimizer prompt must reject visible version text or hover title as the only name');
						  assert(uiPrompt.includes('group/progressbar 完整 `progressLabel`'), 'ui optimizer prompt must preserve complete progress labels on model-usage focus groups');
						  assert(uiPrompt.includes('百分比、token、额度'), 'ui optimizer prompt must cover percentage, token, and quota duplicate text');
						  assert(uiPrompt.includes('纯视觉重复短文本必须 `aria-hidden`'), 'ui optimizer prompt must hide duplicate visual-only text in aggregate groups');
						  assert(uiPrompt.includes('`.llm-badge`'), 'ui optimizer prompt must cover llm-badge truncation');
						  assert(uiPrompt.includes('会被 CSS 截断'), 'ui optimizer prompt must handle CSS-truncated visible short text');
						  assert(uiPrompt.includes('完整 `title/aria-label`'), 'ui optimizer prompt must keep complete title and aria-label on truncated chips');
								  assert(uiPrompt.includes('给人眼看的短文本'), 'ui optimizer prompt must distinguish human-visible short text');
								  assert(uiPrompt.includes('给程序读的完整名称'), 'ui optimizer prompt must distinguish programmatic complete names');
								  assert(uiPrompt.includes('被聚合名称覆盖的重复视觉文本要隐藏'), 'ui optimizer prompt must hide visual text already covered by aggregate names');
								  assert(uiPrompt.includes('被截断的可见文本要补完整程序化名称'), 'ui optimizer prompt must preserve complete programmatic names for truncated visible text');
								  assert(uiPrompt.includes('短状态、过往卡和批量操作反馈完整闭环'), 'ui optimizer prompt must preserve 11:48 short-state, history-card, and bulk-action feedback guidance');
								  assert(uiPrompt.includes('11:48 专属检查'), 'ui optimizer prompt must keep 11:48 boundary explicit');
								  assert(uiPrompt.includes('办公室/服务器状态胶囊'), 'ui optimizer prompt must cover office and server status capsules');
								  assert(uiPrompt.includes('任务板过往任务卡'), 'ui optimizer prompt must cover task-board history cards');
								  assert(uiPrompt.includes('批量取消排队操作'), 'ui optimizer prompt must cover bulk queued-task cancel feedback');
								  assert(uiPrompt.includes('不要重复 11:20 的版本徽章/模型用量内部文本分层'), 'ui optimizer prompt must keep 11:48 separate from 11:20 compact text layering');
								  assert(uiPrompt.includes('不要重复 12:38 的舞台视图提示/附件失败反馈规则'), 'ui optimizer prompt must keep 11:48 separate from 12:38 view/attachment feedback');
								  assert(uiPrompt.includes('不要重复 15:41 的折叠分组/模型空态规则'), 'ui optimizer prompt must keep 11:48 separate from 15:41 group/model empty-state rules');
								  assert(uiPrompt.includes('状态胶囊若显示压缩短文本'), 'ui optimizer prompt must detect compressed status capsule text');
								  assert(uiPrompt.includes('初始渲染与动态刷新路径都必须同点同步完整 `title/aria-label`'), 'ui optimizer prompt must synchronize status capsule names on initial and dynamic refresh paths');
								  assert(uiPrompt.includes('不能只靠父卡聚合名称'), 'ui optimizer prompt must reject parent-card-only names for short states');
								  assert(uiPrompt.includes('完整 `cardLabel`'), 'ui optimizer prompt must reuse complete card labels for history cards');
								  assert(uiPrompt.includes('并声明 `role=group`'), 'ui optimizer prompt must require group semantics on history cards');
								  assert(uiPrompt.includes('状态、执行方、ID、更新时间/完成时间和问/解摘要'), 'ui optimizer prompt must include full history-card state, owner, id, time, and ask/answer summary');
								  assert(uiPrompt.includes('不能只显示问/解、短 ID 或 hover 残片'), 'ui optimizer prompt must reject short ask/answer/id/hover fragments as history-card names');
								  assert(uiPrompt.includes('空队列、用户取消、成功和部分失败四类就近反馈'), 'ui optimizer prompt must require all four bulk-cancel terminal feedback states');
								  assert(uiPrompt.includes('不得停留在“正在取消”'), 'ui optimizer prompt must not leave successful bulk cancel feedback in in-progress text');
								  assert(uiPrompt.includes('“已跳过: 工单已完成”这类已完成跳过要归成功语气'), 'ui optimizer prompt must classify completed-ticket skips as successful tone');
									  assert(uiPrompt.includes('连续两轮同类短状态/历史卡/批量反馈问题要合并为同一问题簇再派修'), 'ui optimizer prompt must merge repeated similar issues before dispatch');
									  assert(uiPrompt.includes('同一 source case/report 在 24 小时内不得重复触发新的自省队列'), 'ui optimizer prompt must prevent same-source repeated self-reflection triggers within 24 hours');
									  assert(uiPrompt.includes('案例条目哈希或来源锚点确实变化'), 'ui optimizer prompt must allow retrigger only when case hash or source anchor changes');
									  assert(uiPrompt.includes('动态分区和装饰箭头结构语义'), 'ui optimizer prompt must preserve 12:48 dynamic-section and decorative-arrow structure guidance');
									  assert(uiPrompt.includes('12:48 专属检查'), 'ui optimizer prompt must keep 12:48 boundary explicit');
									  assert(uiPrompt.includes('任务板动态分区、队列/版本历史折叠箭头和任务板空态'), 'ui optimizer prompt must cover task-board sections, queue/version arrows, and task-board empty states');
									  assert(uiPrompt.includes('不要重复 11:48 的短状态/过往卡/批量反馈闭环'), 'ui optimizer prompt must keep 12:48 separate from 11:48 short-state guidance');
									  assert(uiPrompt.includes('不要重复 15:41 的任务板一级/agent 折叠 summary 完整名称'), 'ui optimizer prompt must keep 12:48 separate from 15:41 summary naming guidance');
									  assert(uiPrompt.includes('不要重复 18:45 的动态进展脱敏规则'), 'ui optimizer prompt must keep 12:48 separate from 18:45 progress redaction guidance');
									  assert(uiPrompt.includes('`tb-section` 动态分区必须有稳定 `role=region`'), 'ui optimizer prompt must require region semantics on dynamic task-board sections');
									  assert(uiPrompt.includes('分区名称要覆盖“进行中/队列/过往/维修任务”'), 'ui optimizer prompt must name concrete task-board section categories');
									  assert(uiPrompt.includes('显示数量、总量/上限或维修特权上下文'), 'ui optimizer prompt must include counts, limits, or repair context in section names');
									  assert(uiPrompt.includes('不能只靠视觉 `h3` 或父卡名称'), 'ui optimizer prompt must reject h3-only or parent-card-only section semantics');
									  assert(uiPrompt.includes('版本历史 `.tw`、队列 `.qcaret`'), 'ui optimizer prompt must cover version and queue caret decoration');
									  assert(uiPrompt.includes('必须 `aria-hidden="true"` 并让 summary/button 自身承担完整名称'), 'ui optimizer prompt must hide decorative arrows and keep complete summary/button names');
									  assert(uiPrompt.includes('避免装饰符号进入程序化文本树'), 'ui optimizer prompt must prevent decorative symbols from polluting programmatic text');
									  assert(uiPrompt.includes('`taskBoardEmpty()` 或等价空态 helper'), 'ui optimizer prompt must cover the task-board empty-state helper');
									  assert(uiPrompt.includes('可见文本、hover `title` 和 `aria-label` 同源'), 'ui optimizer prompt must keep visible, title, and aria-label text in sync for empty states');
									  assert(uiPrompt.includes('结构层 UI 要先分清 region/summary/status 的语义锚点和纯视觉装饰'), 'ui optimizer prompt must distinguish structural semantics from visual decoration');
									  assert(uiPrompt.includes('视图提示和附件失败反馈同点进入状态语义'), 'ui optimizer prompt must preserve 12:38 view-hint and attachment-failure semantic guidance');
							  assert(uiPrompt.includes('12:38 专属检查'), 'ui optimizer prompt must keep 12:38 boundary separate from earlier cases');
							  assert(uiPrompt.includes('舞台视图提示'), 'ui optimizer prompt must cover the stage view hint');
							  assert(uiPrompt.includes('附件粘贴入口'), 'ui optimizer prompt must cover the attachment paste entry');
							  assert(uiPrompt.includes('任务板/派单反馈 tone'), 'ui optimizer prompt must cover task-board and dispatch feedback tone');
							  assert(uiPrompt.includes('不要重复 11:20 的版本徽章/模型用量内部文本分层'), 'ui optimizer prompt must keep 12:38 separate from the 11:20 compact button rule');
							  assert(uiPrompt.includes('不要重复 11:20'), 'ui optimizer prompt must preserve the 12:38/11:20 boundary');
							  assert(uiPrompt.includes('不要重复 06:15 的附件列表/页头/短进展规则'), 'ui optimizer prompt must keep 12:38 separate from the 06:15 attachment-list rule');
							  assert(uiPrompt.includes('`#stageHint`'), 'ui optimizer prompt must name the stageHint element');
							  assert(uiPrompt.includes('`setView()`'), 'ui optimizer prompt must verify setView refresh semantics');
							  assert(uiPrompt.includes('`role=status`'), 'ui optimizer prompt must require status semantics on stage hints');
							  assert(uiPrompt.includes('`aria-live`'), 'ui optimizer prompt must require live semantics on stage hints');
							  assert(uiPrompt.includes('全部 file item'), 'ui optimizer prompt must pass all pasted file items to the shared attachment handler');
							  assert(uiPrompt.includes('`addImageFiles()`'), 'ui optimizer prompt must name the shared image attachment handler');
							  assert(uiPrompt.includes('`未识别到图片附件`'), 'ui optimizer prompt must name the no-image attachment feedback');
							  assert(uiPrompt.includes('`已跳过 N 个非图片文件`'), 'ui optimizer prompt must name skipped non-image attachment feedback');
							  assert(uiPrompt.includes('`taskBoardFeedbackTone()`'), 'ui optimizer prompt must cover the feedback tone helper');
							  assert(uiPrompt.includes('`未识别/最多/超过/跳过/缺少/不能为空` 归为 warn'), 'ui optimizer prompt must classify invalid input and attachment-limit feedback as warn');
							  assert(uiPrompt.includes('失败/错误/超时/异常归 err'), 'ui optimizer prompt must keep real failures in err tone');
							  assert(uiPrompt.includes('visible text、`title`、`aria-label`、role/live/tone'), 'ui optimizer prompt must synchronize visible text, title, aria-label, role/live, and tone for short status feedback');
							  assert(uiPrompt.includes('监控卡容器名称和反馈语气一致'), 'ui optimizer prompt must preserve 13:38 monitoring-card container and feedback-tone guidance');
							  assert(uiPrompt.includes('13:38 专属检查'), 'ui optimizer prompt must keep 13:38 boundary separate from adjacent cases');
							  assert(uiPrompt.includes('办公室工位卡'), 'ui optimizer prompt must cover office workstation cards');
							  assert(uiPrompt.includes('服务器机房卡'), 'ui optimizer prompt must cover server-room cards');
							  assert(uiPrompt.includes('正常排队反馈 tone'), 'ui optimizer prompt must cover normal queue-wait feedback tone');
							  assert(uiPrompt.includes('不要重复 12:38 的舞台视图提示/附件失败反馈规则'), 'ui optimizer prompt must keep 13:38 separate from the 12:38 view and attachment rule');
							  assert(uiPrompt.includes('不要重复 14:58 的模型用量卡聚合名称'), 'ui optimizer prompt must keep 13:38 separate from the 14:58 model-usage card rule');
							  assert(uiPrompt.includes('容器本体必须有稳定 `role=group`'), 'ui optimizer prompt must require stable role=group on monitoring-card containers');
							  assert(uiPrompt.includes('完整 `title` 和完整 `aria-label`'), 'ui optimizer prompt must require complete title and aria-label on monitoring-card containers');
							  assert(uiPrompt.includes('初始渲染与动态刷新路径都要同点同步'), 'ui optimizer prompt must check initial and dynamic refresh paths for monitoring-card names');
							  assert(uiPrompt.includes('角色、状态、任务/工具、IP/队列'), 'ui optimizer prompt must include complete aggregate fields for office and server cards');
							  assert(uiPrompt.includes('hover `title` 与 `aria-label` 不能表达两套不一致含义'), 'ui optimizer prompt must reject inconsistent hover title and aria-label text');
							  assert(uiPrompt.includes('`已派单,等待队列接收`'), 'ui optimizer prompt must keep dispatch queue-wait feedback in ok tone');
							  assert(uiPrompt.includes('`已提交启用,等待队列刷新`'), 'ui optimizer prompt must keep enable queue-refresh feedback in ok tone');
								  assert(uiPrompt.includes('成功型排队/接收中反馈优先归 ok'), 'ui optimizer prompt must prioritize ok tone for successful queued/accepted feedback');
								  assert(uiPrompt.includes('不能被 `等待/待` 这类粗关键词误判为 warn'), 'ui optimizer prompt must not classify ordinary queue waiting as warn');
								  assert(uiPrompt.includes('输入失败仍归 warn'), 'ui optimizer prompt must keep invalid input feedback as warn');
								  assert(uiPrompt.includes('正常等待队列接收要与输入失败、错误和超时区分'), 'ui optimizer prompt must distinguish ordinary queue acceptance from invalid input, errors, and timeouts');
								  assert(uiPrompt.includes('成功反馈和审批监控卡同点维护'), 'ui optimizer prompt must preserve 14:41 successful-feedback and approval-monitor-card guidance');
								  assert(uiPrompt.includes('14:41 专属检查'), 'ui optimizer prompt must keep 14:41 boundary separate from adjacent cases');
								  assert(uiPrompt.includes('任务板反馈胶囊'), 'ui optimizer prompt must cover task-board feedback pills');
								  assert(uiPrompt.includes('任务板摘要 live region'), 'ui optimizer prompt must cover task-board summary live regions');
								  assert(uiPrompt.includes('办公室审批/工具监控卡'), 'ui optimizer prompt must cover office approval and tool monitor cards');
								  assert(uiPrompt.includes('不要重复 13:38 的办公室/服务器容器通用 role/name 规则'), 'ui optimizer prompt must keep 14:41 separate from 13:38 monitor-container guidance');
								  assert(uiPrompt.includes('不要重复 08:14 的版本分组/control-room 行级名称规则'), 'ui optimizer prompt must keep 14:41 separate from 08:14 version/control-room guidance');
								  assert(uiPrompt.includes('`已启用: 正在执行 #id`'), 'ui optimizer prompt must keep active enabled-execution feedback in ok tone');
								  assert(uiPrompt.includes('`已启用并开始执行`'), 'ui optimizer prompt must keep enabled-and-started feedback in ok tone');
								  assert(uiPrompt.includes('`已入队`'), 'ui optimizer prompt must keep enqueued feedback in ok tone');
								  assert(uiPrompt.includes('`已加入`'), 'ui optimizer prompt must keep joined feedback in ok tone');
								  assert(uiPrompt.includes('`已提交`'), 'ui optimizer prompt must keep submitted feedback in ok tone');
								  assert(uiPrompt.includes('在 `正在/中…/等待/待` 等粗关键词前优先归 ok'), 'ui optimizer prompt must rank successful business-result prefixes before coarse warn keywords');
								  assert(uiPrompt.includes('`updateTaskBoardHint()`'), 'ui optimizer prompt must cover the task-board hint refresh helper');
								  assert(uiPrompt.includes('每轮同步 `role`、`aria-live`、`aria-atomic` 和 `data-feedback`'), 'ui optimizer prompt must refresh live-region role, live mode, atomicity, and feedback data every cycle');
								  assert(uiPrompt.includes('错误态才用 `role=alert`/`aria-live=assertive`'), 'ui optimizer prompt must reserve alert/assertive semantics for real errors');
								  assert(uiPrompt.includes('普通摘要和成功反馈必须恢复 `role=status`/`aria-live=polite`'), 'ui optimizer prompt must restore status/polite semantics for ordinary summaries and successful feedback');
								  assert(uiPrompt.includes('human gate'), 'ui optimizer prompt must include human gate information in monitor-card names');
								  assert(uiPrompt.includes('permission_wait'), 'ui optimizer prompt must include permission-wait information in monitor-card names');
								  assert(uiPrompt.includes('工具监控卡的 `title` 与 `aria-label` 必须同点复用完整文本'), 'ui optimizer prompt must reuse complete title text in tool monitor aria-labels');
								  assert(uiPrompt.includes('`officeActorHtml()`'), 'ui optimizer prompt must check the office actor initial render path');
									  assert(uiPrompt.includes('`renderOfficeAgent()`'), 'ui optimizer prompt must check the office actor dynamic refresh path');
									  assert(uiPrompt.includes('反馈 tone 先按业务结果分层'), 'ui optimizer prompt must classify feedback tone by business result before generic keywords');
									  assert(uiPrompt.includes('审批、工具调用和队列状态卡片的 `title`/`aria-label` 不一致'), 'ui optimizer prompt must treat title/aria-label mismatch on approval, tool, and queue-state cards as semantic debt');
									  assert(uiPrompt.includes('任务板折叠分组和模型空态完整名称'), 'ui optimizer prompt must preserve 15:41 task-board group and model-empty-state naming guidance');
									  assert(uiPrompt.includes('15:41 专属检查'), 'ui optimizer prompt must keep 15:41 boundary separate from adjacent cases');
									  assert(uiPrompt.includes('任务板一级折叠分组'), 'ui optimizer prompt must cover top-level task-board collapsible groups');
									  assert(uiPrompt.includes('按 agent 折叠分组'), 'ui optimizer prompt must cover per-agent collapsible groups');
									  assert(uiPrompt.includes('agent 队列概览行'), 'ui optimizer prompt must cover agent queue overview rows');
									  assert(uiPrompt.includes('模型用量 body 空态/错误态'), 'ui optimizer prompt must cover model-usage body empty and error states');
									  assert(uiPrompt.includes('不要重复 14:41 的成功反馈/live region/审批工具卡规则'), 'ui optimizer prompt must keep 15:41 separate from 14:41 success-feedback guidance');
									  assert(uiPrompt.includes('不要重复 13:38 的办公室/服务器监控卡容器规则'), 'ui optimizer prompt must keep 15:41 separate from 13:38 monitor-container guidance');
									  assert(uiPrompt.includes('`queueSection()`'), 'ui optimizer prompt must cover queueSection summaries');
									  assert(uiPrompt.includes('`queueAgentBlock()`'), 'ui optimizer prompt must cover queueAgentBlock summaries');
									  assert(uiPrompt.includes('`summary` 必须同步完整 `title/aria-label`'), 'ui optimizer prompt must synchronize complete title and aria-label on summaries');
									  assert(uiPrompt.includes('运行中/排队中数量'), 'ui optimizer prompt must include running and queued counts in group names');
									  assert(uiPrompt.includes('可取消/批量取消状态'), 'ui optimizer prompt must include cancel and bulk-cancel state in group names');
									  assert(uiPrompt.includes('`queueAgentOverview()`'), 'ui optimizer prompt must cover queueAgentOverview rows');
									  assert(uiPrompt.includes('`.qagent-row` 必须有 `role=group/title/aria-label`'), 'ui optimizer prompt must require group role, title, and aria-label on qagent rows');
									  assert(uiPrompt.includes('四个计数 pill 必须各自保留 `title/aria-label`'), 'ui optimizer prompt must require complete names on all count pills');
									  assert(uiPrompt.includes('裸 `span` 和视觉数字'), 'ui optimizer prompt must reject bare spans and visual numbers as the only queue state');
									  assert(uiPrompt.includes('`renderLlmUsage()`'), 'ui optimizer prompt must cover renderLlmUsage body states');
									  assert(uiPrompt.includes('读取中、读取失败、暂无数据分支'), 'ui optimizer prompt must cover loading, failure, and empty model-usage body branches');
									  assert(uiPrompt.includes('`title` 与 `aria-label` 同点维护完整状态'), 'ui optimizer prompt must synchronize title and aria-label for empty/error body states');
									  assert(uiPrompt.includes('错误态继续用 `role=alert`'), 'ui optimizer prompt must keep alert semantics for model-usage body errors');
									  assert(uiPrompt.includes('折叠、截断、按行重复或作为空态/错误态显示'), 'ui optimizer prompt must generalize complete names to collapsed, truncated, repeated, empty, and error states');
									  assert(uiPrompt.includes('不能只靠视觉片段、tooltip 或单一 aria 字段表达状态'), 'ui optimizer prompt must reject visual snippets, tooltips, or a single aria field as the only semantic state');
									  assert(uiPrompt.includes('监控文本脱敏和读取失败 live 状态边界'), 'ui optimizer prompt must preserve 16:41 redaction and live-state boundary guidance');
									  assert(uiPrompt.includes('16:41 专属检查'), 'ui optimizer prompt must keep 16:41 boundary separate from adjacent cases');
									  assert(uiPrompt.includes('队列任务详情'), 'ui optimizer prompt must cover queue task details for display redaction');
									  assert(uiPrompt.includes('办公室/链路图任务摘要'), 'ui optimizer prompt must cover office and flow-map task summaries for display redaction');
									  assert(uiPrompt.includes('事件流更新时间 `#ts`'), 'ui optimizer prompt must cover event timestamp live state');
									  assert(uiPrompt.includes('任务板 header 读取失败'), 'ui optimizer prompt must cover task-board header failure state');
									  assert(uiPrompt.includes('不要重复 15:41 的折叠分组/模型空态完整名称规则'), 'ui optimizer prompt must keep 16:41 separate from 15:41 group/model-empty guidance');
									  assert(uiPrompt.includes('不要重复 14:41 的成功反馈/live region/审批工具卡规则'), 'ui optimizer prompt must keep 16:41 separate from 14:41 success-feedback guidance');
									  assert(uiPrompt.includes('`redactUiText()`'), 'ui optimizer prompt must name the display redaction helper');
									  assert(uiPrompt.includes('只限 UI 展示层的 visible text'), 'ui optimizer prompt must limit auto redaction to UI display text');
									  assert(uiPrompt.includes('`title`、`aria-label`、hover 名称和任务摘要'), 'ui optimizer prompt must list redaction display targets');
									  assert(uiPrompt.includes('不得改写原始 queue payload、engine event log、调试日志'), 'ui optimizer prompt must forbid rewriting raw payloads, event logs, and debug logs');
									  assert(uiPrompt.includes('queueId/taskId、模型名或非敏感业务状态'), 'ui optimizer prompt must preserve identifiers, model names, and non-secret status text');
									  assert(uiPrompt.includes('`Bearer`'), 'ui optimizer prompt must include Bearer in sensitive matching baseline');
									  assert(uiPrompt.includes('`api_key`/`api-key`'), 'ui optimizer prompt must include api key variants in sensitive matching baseline');
									  assert(uiPrompt.includes('`token`'), 'ui optimizer prompt must include token in sensitive matching baseline');
									  assert(uiPrompt.includes('`secret`'), 'ui optimizer prompt must include secret in sensitive matching baseline');
									  assert(uiPrompt.includes('`password`'), 'ui optimizer prompt must include password in sensitive matching baseline');
									  assert(uiPrompt.includes('`NEW_API_TOKEN`'), 'ui optimizer prompt must include NEW_API_TOKEN in sensitive matching baseline');
									  assert(uiPrompt.includes('`ANTHROPIC_API_KEY`'), 'ui optimizer prompt must include ANTHROPIC_API_KEY in sensitive matching baseline');
									  assert(uiPrompt.includes('`OPENAI_API_KEY`'), 'ui optimizer prompt must include OPENAI_API_KEY in sensitive matching baseline');
									  assert(uiPrompt.includes('owner_decision'), 'ui optimizer prompt must route broad or debugging-impacting redaction to owner_decision');
									  assert(uiPrompt.includes('`cleanTaskText()`'), 'ui optimizer prompt must cover cleanTaskText redaction entry');
									  assert(uiPrompt.includes('`queueTaskText()`'), 'ui optimizer prompt must cover queueTaskText redaction entry');
									  assert(uiPrompt.includes('`taskBoardOutputText()`'), 'ui optimizer prompt must cover taskBoardOutputText redaction entry');
									  assert(uiPrompt.includes('展示脱敏再做压缩/截断'), 'ui optimizer prompt must redact display text before compression or truncation');
									  assert(uiPrompt.includes('`pollEvents()` 成功/失败分支'), 'ui optimizer prompt must cover pollEvents success and failure branches');
									  assert(uiPrompt.includes('`role=status/alert` 和 `aria-live=polite/assertive`'), 'ui optimizer prompt must synchronize role and aria-live for event timestamps');
										  assert(uiPrompt.includes('`pollQueue()` 失败分支'), 'ui optimizer prompt must cover pollQueue failure branch');
										  assert(uiPrompt.includes('`queueHint` 与正文错误态同步'), 'ui optimizer prompt must synchronize queueHint with body error state');
										  assert(uiPrompt.includes('不得在未获批准时重写多源状态聚合、任务状态机或队列语义'), 'ui optimizer prompt must require owner approval for multi-source status aggregation and state-machine changes');
										  assert(uiPrompt.includes('事件/任务监控文本先脱敏再进入可见和程序化名称'), 'ui optimizer prompt must preserve 17:41 event/task monitor text redaction guidance');
										  assert(uiPrompt.includes('17:41 专属检查'), 'ui optimizer prompt must keep 17:41 boundary separate from adjacent cases');
										  assert(uiPrompt.includes('页头更新时间、办公室/工位任务摘要、交接短状态和事件 feed'), 'ui optimizer prompt must cover header timestamp, office/workstation summaries, handoff short state, and event feed');
										  assert(uiPrompt.includes('不要重复 16:41 的队列详情/header 失败同步规则'), 'ui optimizer prompt must keep 17:41 separate from 16:41 queue/header failure guidance');
										  assert(uiPrompt.includes('不要重复 15:41 的折叠分组/模型空态完整名称规则'), 'ui optimizer prompt must keep 17:41 separate from 15:41 group/model-empty guidance');
										  assert(uiPrompt.includes('JSON/带引号 key 写法'), 'ui optimizer prompt must cover JSON and quoted-key secret formats');
										  assert(uiPrompt.includes('"OPENAI_API_KEY":"..."'), 'ui optimizer prompt must include JSON OPENAI_API_KEY as a sensitive matching example');
										  assert(uiPrompt.includes("`'api_key': '...'`"), 'ui optimizer prompt must include quoted api_key as a sensitive matching example');
										  assert(uiPrompt.includes('`access_token`'), 'ui optimizer prompt must include access_token in the 17:41 sensitive baseline');
										  assert(uiPrompt.includes('`refresh_token`'), 'ui optimizer prompt must include refresh_token in the 17:41 sensitive baseline');
										  assert(uiPrompt.includes('先脱敏再进入 visible text'), 'ui optimizer prompt must redact before visible and programmatic text');
										  assert(uiPrompt.includes('事件摘要或程序化名称'), 'ui optimizer prompt must include event summaries and programmatic names in display redaction targets');
										  assert(uiPrompt.includes('`taskText()`'), 'ui optimizer prompt must cover taskText as a task text entry');
										  assert(uiPrompt.includes('`ev.goal`、`taskGoals`'), 'ui optimizer prompt must cover ev.goal and taskGoals sources');
										  assert(uiPrompt.includes('任务目标、失败原因或事件摘要'), 'ui optimizer prompt must cover task goals, failure reasons, and event summaries');
										  assert(uiPrompt.includes('页头 `#ts` 初始、成功刷新、失败分支'), 'ui optimizer prompt must cover #ts initial, success, and failure branches');
										  assert(uiPrompt.includes('办公室 `.office-task`、工位 `#tk-*`、交接 `#hf-*`'), 'ui optimizer prompt must cover office task, workstation task, and handoff short-state selectors');
											  assert(uiPrompt.includes('自己的稳定 `aria-label`'), 'ui optimizer prompt must require local aria-labels for individually readable short states');
											  assert(uiPrompt.includes('不能只靠父容器聚合名或 hover `title`'), 'ui optimizer prompt must reject parent-only or title-only short-state semantics');
											  assert(uiPrompt.includes('事件 feed 若渲染必须用 `role=list` 容器、`role=listitem` 行和 `role=status` 空态'), 'ui optimizer prompt must require list/listitem/status semantics for event feed');
											  assert(uiPrompt.includes('事件行的完整 `title/aria-label` 同样要先展示脱敏'), 'ui optimizer prompt must redact event-row titles and aria-labels before display');
											  assert(uiPrompt.includes('动态进展脱敏和截断短状态完整名称'), 'ui optimizer prompt must preserve 18:45 dynamic progress and truncated short-state guidance');
											  assert(uiPrompt.includes('18:45 专属检查'), 'ui optimizer prompt must keep 18:45 boundary separate from adjacent cases');
											  assert(uiPrompt.includes('任务板动态进展短文本、服务器 IP 行和链路图节点任务短文本'), 'ui optimizer prompt must cover task-board progress, server IP, and flow-node task short text');
											  assert(uiPrompt.includes('不要重复 17:41 的事件 feed/页头/工位短状态规则'), 'ui optimizer prompt must keep 18:45 separate from 17:41 event/header/workstation guidance');
											  assert(uiPrompt.includes('不要重复 16:41 的队列详情/header 失败同步规则'), 'ui optimizer prompt must keep 18:45 separate from 16:41 queue/header failure guidance');
											  assert(uiPrompt.includes('`taskBoardProgressShort()`'), 'ui optimizer prompt must cover taskBoardProgressShort');
											  assert(uiPrompt.includes('先 `redactUiText()` 再 `queueCompactText()`/压缩截断'), 'ui optimizer prompt must redact dynamic progress before compacting or truncating');
											  assert(uiPrompt.includes('失败原因、任务目标和进展摘要不能先截断再脱敏'), 'ui optimizer prompt must forbid truncating sensitive progress before redaction');
											  assert(uiPrompt.includes('服务器卡片 IP 行'), 'ui optimizer prompt must cover server card IP rows');
											  assert(uiPrompt.includes('`ipText`/`ipLabel`'), 'ui optimizer prompt must require ipText/ipLabel complete names');
											  assert(uiPrompt.includes('`IP 未配置`'), 'ui optimizer prompt must require visible empty IP placeholder');
											  assert(uiPrompt.includes('`.office-agent.server .office-task`'), 'ui optimizer prompt must cover the server office-task selector');
											  assert(uiPrompt.includes('同步 visible text、`title`、`aria-label`'), 'ui optimizer prompt must synchronize server IP visible text, title, and aria-label');
											  assert(uiPrompt.includes('链路图节点 `.ftask`'), 'ui optimizer prompt must cover flow node ftask text');
											  assert(uiPrompt.includes('`nodeTaskLabel`'), 'ui optimizer prompt must require complete node task labels');
												  assert(uiPrompt.includes('`displayTask()`/`taskText()`'), 'ui optimizer prompt must reuse redacted display task entry points for flow nodes');
												  assert(uiPrompt.includes('动态进展、短状态和空白占位不是装饰'), 'ui optimizer prompt must treat progress, short states, and empty placeholders as semantic content');
												  assert(uiPrompt.includes('被截断、折叠、空白或单独读取的监控文本'), 'ui optimizer prompt must cover truncated, collapsed, empty, or individually readable monitor text');
												  assert(uiPrompt.includes('输入失败反馈和附件托盘同点维护'), 'ui optimizer prompt must preserve 21:48 input-failure and attachment-tray same-point guidance');
												  assert(uiPrompt.includes('21:48 专属检查'), 'ui optimizer prompt must keep 21:48 boundary separate from adjacent cases');
												  assert(uiPrompt.includes('底部派单栏、图片附件托盘、任务板/派单反馈胶囊'), 'ui optimizer prompt must cover dispatch bar, attachment tray, and feedback pills for 21:48');
												  assert(uiPrompt.includes('不要重复 05:14 的非图片附件/超限附件就近反馈'), 'ui optimizer prompt must keep 21:48 separate from 05:14 invalid-attachment feedback');
												  assert(uiPrompt.includes('06:15 的附件托盘 `role=list/listitem`'), 'ui optimizer prompt must keep 21:48 separate from 06:15 list/listitem tray semantics');
												  assert(uiPrompt.includes('11:48 的短状态/过往卡/批量反馈'), 'ui optimizer prompt must keep 21:48 separate from 11:48 short-state and bulk feedback');
												  assert(uiPrompt.includes('12:48 的结构层 region/装饰箭头'), 'ui optimizer prompt must keep 21:48 separate from 12:48 structure semantics');
												  assert(uiPrompt.includes('16:41/17:41/18:45 的展示脱敏与短状态规则'), 'ui optimizer prompt must keep 21:48 separate from display-redaction and short-state rules');
												  assert(uiPrompt.includes('`#attachTray` 初始 DOM 与 `renderImageAttachments()` 动态空态/有附件态'), 'ui optimizer prompt must check attachment tray initial and dynamic render paths');
												  assert(uiPrompt.includes('同点同步 `title` 和 `aria-label`'), 'ui optimizer prompt must synchronize attachment tray title and aria-label');
												  assert(uiPrompt.includes('hover 审查、读屏和 GUI grounding'), 'ui optimizer prompt must align hover review, screen reader, and GUI grounding names');
												  assert(uiPrompt.includes('附件删除按钮必须复用同一个 fallback 名称'), 'ui optimizer prompt must require a shared fallback name for attachment delete buttons');
												  assert(uiPrompt.includes('空文件名不得退化成 `删除图片 `'), 'ui optimizer prompt must reject blank attachment delete titles');
												  assert(uiPrompt.includes('`setInlineStatus()` 与 `setComposeFeedback()` 遇到 warn/err'), 'ui optimizer prompt must cover warn and err feedback helpers');
												  assert(uiPrompt.includes('都必须使用 `aria-live=assertive` 与 `aria-atomic=true`'), 'ui optimizer prompt must make warn and err feedback assertive and atomic');
												  assert(uiPrompt.includes('err 仍保留 `role=alert`'), 'ui optimizer prompt must keep role=alert for error feedback');
												  assert(uiPrompt.includes('warn 不升级成 alert 但要比 info/polite 更及时'), 'ui optimizer prompt must distinguish warn assertive feedback from error alerts');
												  assert(uiPrompt.includes('输入失败、附件失败和空态不是装饰提示'), 'ui optimizer prompt must treat input failures, attachment failures, and empty states as semantic feedback');
												  assert(uiPrompt.includes('同源 `title/aria-label/live` 闭环'), 'ui optimizer prompt must require same-source title, aria-label, and live-region closure for input feedback');

											  const loop = read('shared/agents/ui-optimizer/loop.sh');
  assert(loop.includes('CASE_FILE="$CASE_DIR/ui-optimization-cases.md"'), 'loop must define learning case file');
  assert(loop.includes('append_learning_case'), 'loop must append learning cases at summary time');
  assert(loop.includes('emit_learning_case_event'), 'loop must emit learning case event at summary time');
  assert(loop.includes('append-learning-case-event.js'), 'loop must use the locked learning case event writer');
  const eventWriter = read('shared/agents/ui-optimizer/append-learning-case-event.js');
  assert(eventWriter.includes("type: 'learning_case.appended'"), 'event writer must use stable learning case event type');
  assert(eventWriter.includes('appendJsonlWithLock'), 'event writer must append JSONL through the lock helper');
  assert(eventWriter.includes('.learning-case.lock'), 'event writer must use a dedicated learning-case lock');
  assert(loop.includes('UI_OPT_TASK_ID'), 'loop learning-case events must preserve taskId when supplied');
  assert(loop.includes('UI_OPT_QUEUE_ID'), 'loop learning-case events must preserve queueId when supplied');
  assert(loop.includes('UI_OPT_ROOT_QUEUE_ID'), 'loop learning-case events must preserve rootQueueId when supplied');
  assert(loop.includes('SELF_REFLECTION_TRIGGER_COOLDOWN_SECONDS'), 'loop must define a self-reflection trigger cooldown window');
  assert(loop.includes('UI_OPT_SOURCE_CASE_ANCHOR'), 'loop must key trigger cooldown by source case anchor when supplied');
  assert(loop.includes('UI_OPT_SOURCE_CASE_HASH'), 'loop must key trigger cooldown by source case hash when supplied');
  assert(loop.includes('同一 source case/hash 在 24 小时冷却期内已触发'), 'loop must skip repeated same-source self-reflection triggers inside the cooldown window');
  assert(loop.includes('--case-title "$UI_OPT_SOURCE_CASE_TITLE"'), 'loop must pass an explicit source case title to the trigger when supplied');
  assert(eventWriter.includes('queueAgent: env.UI_OPT_QUEUE_AGENT'), 'event writer must preserve queueAgent when supplied');

  const secretaryTools = read('projects/控制台/secretary-tools.js');
  assert(secretaryTools.includes("['learning-cases'"), 'secretary background package must include learning-cases README');
  assert(secretaryTools.includes("['ui-optimization-cases'"), 'secretary background package must include ui optimization cases');

  const secretaryPrompt = read('shared/agents/secretary/prompt.md');
  const ceoPrompt = read('shared/agents/orchestrator/prompt.md');
  assert(secretaryPrompt.includes('board/learning-cases/'), 'secretary must reference learning cases');
  assert(ceoPrompt.includes('board/learning-cases/'), 'CEO must reference learning cases');
  assert(secretaryPrompt.includes('参考案例:'), 'secretary must cite related learning case');
  assert(ceoPrompt.includes('参考案例:'), 'CEO must cite related learning case');
  assert(ceoPrompt.includes('secretary -> CEO -> supervisor'), 'CEO must retain front-door task chain evidence');

  for (const agent of ['board-deepseek', 'board-glm52', 'board-opus48', 'board-gpt55']) {
    const prompt = read(`shared/agents/${agent}/prompt.md`);
    const meta = json(`shared/agents/${agent}/agent.json`);
    assert(prompt.includes('board/learning-cases/'), `${agent} prompt must reference learning cases`);
    assert(prompt.includes('参考案例:') || prompt.includes('参考原则:'), `${agent} prompt must require case citation`);
    assert((meta.read_paths || []).includes('board/learning-cases/'), `${agent} read_paths must include learning cases`);
  }

  const uiAgent = json('shared/agents/ui-optimizer/agent.json');
  assert((uiAgent.writes || []).includes('board/learning-cases/'), 'ui optimizer must be allowed to write learning cases');

  console.log('learning-cases-policy ok');
}

main();
